config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
                                 sign_in: 'login',
                                 sign_out: 'logout',
                                 registration: 'signup'
                               },
                     controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations'

                     }
  get '/', to: 'users#index', as: :home
  get '/current_user', to: 'current_user#index'

  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/posts', to: 'posts#index', as: :user_posts
  get 'users/:id/posts/new', to: 'posts#new', as: :user_post_new
  get 'users/:id/posts/:post_id', to: 'posts#show', as: :post
  get 'users/:id/posts/:post_id/comment/new', to: 'comments#new', as: :comment
  post 'users/:id/posts/create', to: 'posts#create', as: :posts_create
  post 'users/:id/posts/:post_id/comment/create', to: 'comments#create', as: :comment_create
  post 'users/:id/posts/:post_id/create/like', to: 'likes#create', as: :like_create
  delete 'users/:id/posts/:post_id/delete', to: 'posts#destroy', as: :post_delete
  delete 'users/:id/posts/:post_id/comment/:comment_id/delete', to: 'comments#destroy', as: :comment_delete
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :registerable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self

  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable
  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_many :posts, foreign_key: 'authorId'
  has_many :comments, foreign_key: 'authorId'
  has_many :likes, foreign_key: 'authorId'

  # validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  # validates :postCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def admin?
    role == 'admin'
  end

  def last_three_posts
    posts.reverse_order.first(3)
  end

  def jwt_payload
    super.merge('foo' => 'bar')
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :verify_authenticity_token
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    if resource.persisted?
      render json: {
        status: { code: 200, message: 'Signed up sucessfully.' },
        data: UserSerializer.new(resource).serializable_hash[:data][:attributes]
      }
    else
      render json: {
        status: { message: "User couldn't be created successfully. #{resource.errors.full_messages.to_sentence}" }
      }, status: :unprocessable_entity
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    render json: {
      status: { code: 200, message: 'Logged in sucessfully.' },
      data: UserSerializer.new(resource).serializable_hash[:data][:attributes]
    }, status: :ok
  end

  def respond_to_on_destroy
    if current_user
      render json: {
        status: 200,
        message: 'logged out successfully'
      }, status: :ok
    else
      render json: {
        status: 401,
        message: "Couldn't find an active session."
      }, status: :unauthorized
    end
  end

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:post])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current = current_user
  end

  def show
    @user = current_user
    # @user = User.find(params[:id])
    @post = Post.where(authorId: @user.id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <body>
  <%= render 'shared/navbar' %>
  <div class='container' >
    <div class='header'>
      <h2 class='section-title'> Users </h2>
    </div>

    <% @users.order(:postCounter).reverse_order.each do |user| %>
      <%= link_to user_path(user.id), class:'User' do %>
        <div class='user-container'>
          <img class='user-image' src='<%= user.photo %>'>
          <div class='user-data'>
            <h3> <%= user.name %> </h3>
            <p>Number posts: <%= user.postCounter %> </p>
         </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>
<div class='container'>
  <div class='user-container'>
    <img class='user-image' src="<%= @user.photo %>">
    <div class='user-data'>
      <h1 class='name'><%= @user.name %></h1>
      <p class='post-count'>Number posts: <%= @user.postCounter %> </p>
    </div>
  </div>

  <div class='bio'>
    <h2> Bio </h2>
    <p > <%= @user.bio %> </p>
  </div>

<ul class='post-list'>
<% @user.last_three_posts.each do |post|%>
    <%= link_to post_path(@user.id, post.id) do%>
       <li class='post'>
        <h3><%= post.title %></h3>
        <p><%= post.text %></p>
        <div class='comment-like'>
        <p>💬 <%= post.commentsCounter %></p>
        <p>❤️ <%= post.likesCounter %></p>
        </div>
    </li>
    <% end %>
  <% end %>
</ul>

  <%= link_to user_posts_path(@user.id), class:'button' do%>
    <button class='button'> See all posts </button>
  <% end %>
  <% if can? :create , @post%>
  <%= link_to user_post_new_path, class:'button' do%>
    <button class='button'> New Post </button>
  <% end %>
  <%end %>
</div>