config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
                                 sign_in: 'login',
                                 sign_out: 'logout',
                                 registration: 'signup'
                               },
                     controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations'

                     }
  get '/', to: 'users#index', as: :home
  get '/current_user', to: 'current_user#index'

  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/posts', to: 'posts#index', as: :user_posts
  get 'users/:id/posts/new', to: 'posts#new', as: :user_post_new
  get 'users/:id/posts/:post_id', to: 'posts#show', as: :post
  get 'users/:id/posts/:post_id/comment/new', to: 'comments#new', as: :comment
  post 'users/:id/posts/create', to: 'posts#create', as: :posts_create
  post 'users/:id/posts/:post_id/comment/create', to: 'comments#create', as: :comment_create
  post 'users/:id/posts/:post_id/create/like', to: 'likes#create', as: :like_create
  delete 'users/:id/posts/:post_id/delete', to: 'posts#destroy', as: :post_delete
  delete 'users/:id/posts/:post_id/comment/:comment_id/delete', to: 'comments#destroy', as: :comment_delete
end

app/models/api/v1/post.rb
class Api::V1::Post < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'authorId'
  has_many :comments, dependent: :destroy, foreign_key: 'postId'
  has_many :likes, dependent: :destroy, foreign_key: 'postId'

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :text, presence: true, length: { minimum: 3, maximum: 5000 }
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter
  after_destroy :update_post_counter

  def comments
    Comment.where(postId: self).order(created_at: :desc)
  end

  def five_most_recent_comments
    Comment.where(postId: self).order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.update(postCounter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_api_v1_post, only: %i[show edit update destroy]

  # GET /api/v1/posts or /api/v1/posts.json
  def index
    @api_v1_posts = Api::V1::Post.all
  end

  # GET /api/v1/posts/1 or /api/v1/posts/1.json
  def show; end

  # GET /api/v1/posts/new
  def new
    @api_v1_post = Api::V1::Post.new
  end

  # GET /api/v1/posts/1/edit
  def edit; end

  # POST /api/v1/posts or /api/v1/posts.json
  def create
    @api_v1_post = Api::V1::Post.new(api_v1_post_params)

    respond_to do |format|
      if @api_v1_post.save
        format.html { redirect_to api_v1_post_url(@api_v1_post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @api_v1_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api_v1_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/v1/posts/1 or /api/v1/posts/1.json
  def update
    respond_to do |format|
      if @api_v1_post.update(api_v1_post_params)
        format.html { redirect_to api_v1_post_url(@api_v1_post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_v1_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api_v1_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/v1/posts/1 or /api/v1/posts/1.json
  def destroy
    @api_v1_post.destroy

    respond_to do |format|
      format.html { redirect_to api_v1_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_api_v1_post
    @api_v1_post = Api::V1::Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def api_v1_post_params
    params.require(:api_v1_post).permit(:title, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(params[:id])
    @post = Post.where(authorId: @user.id)
    @comment = Comment.where(postId: @post.ids)
  end

  def show
    @user = User.find(params[:id])
    @post = Post.find_by(authorId: current_user.id, id: params[:post_id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(strong_params)
    @post.author = @user
    @post.likesCounter = 0
    @post.commentsCounter = 0

    if @post.save
      flash[:success] = 'Post saved!'
      redirect_to user_path(@user.id)

    else
      flash.now[:error] = 'Please fill all fields'
      render :new, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.destroy

    redirect_to user_path(params[:id])
  end

  private

  def strong_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/index.html.erb
<%= render 'shared/navbar' %>
<div class='container' >
  <h2 class='section-title'> Posts </h2>
  <div class='user-container'>
    <img class='user-image' src="<%= @user.photo %>">
    <div class='user-data'>
      <h3 class='name'><%= @user.name %></h3>
      <p class='post-count'>Number posts: <%= @user.postCounter %> </p>
    </div>
  </div>
  <ul class='post-list'>
    <% @post.each do |post|%>
      <%= link_to post_path(@user.id, post.id) do%>
           <li class='post'>
             <h3><%= post.title %></h3>
             <p><%= post.text %></p>

             <div class='comment-like'>
              <p>💬 <%= post.commentsCounter %></p>
              <p>❤ <%= post.likesCounter %></p>
             </div>

           </li>
           <div class='comment-box'>
             <% post.five_most_recent_comments.includes ([:author]).each do |comment|%>
                <% if comment.postId == post.id %>
                  <div class='comment'>
                    <h3><%= comment.author.name %>:</h3>
                    <p><%= comment.text %></p>
                  </div>
                <% end %>
             <% end %>
           </div>
      <% end %>
  <% end %>
</ul>
<%= link_to user_post_new_path, class:'button' do%>
  <button class='button'> New Post </button>
<% end %>
<%= button_to "Paginations"%>
</div>

app/views/posts/new.html.erb
<%= render 'shared/navbar' %>
<div class='container'>
<h2 class='section-title'>new post</h2>
<h1><%=@post.author %></h1>
  <%= form_with model: @post, url: posts_create_path, class: 'form' do |f| %>
    <%= f.text_field :title, placeholder: 'Title', :required => true, class: 'new-user' %>
    <%= f.text_area :text, placeholder: 'Content', :required => true, class: 'new-text' %>
    <%= f.submit "Submit", class: 'submit-post' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render 'shared/navbar' %>
<div class='container'>
<div>
  <div class='post'>
    <div class='post-header'>
      <p>post # <%= @post.id %> by <%= @user.name %></p>
      <div class='comment-like'>
        <%= link_to comment_path do%>
          <p>💬 <%= @post.commentsCounter%></p>
        <% end %>
        <%= form_with model: Like, url: like_create_path, method: :post do |f| %>
          <%= f.submit '❤' %>
           <%= @post.likesCounter %>

        <% end %>
      </div>
    </div>
    <h3><%= @post.title %></h3>
    <p><%= @post.text %></p>


  </div>
  <ul class='comment-box'>
    <% @post.comments.each do |comment|%>
      <li class='comment'>
      <div class='comment-cont'>
        <h3><%= comment.author.name %>:</h3>
        <p><%= comment.text %></p>
      </div>
        <%= link_to "Delete", comment_delete_path(comment.id, @post.id, comment.id), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>

      </li>
    <% end %>
  </ul>
</div>
  <% if can? :destroy, @post%>
  <%= link_to "Delete Post", post_delete_path(@post.author, @post), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
  <%end%>
</div>